name: Test and Build

on:
  push:
    branches: [main]

env:
  GO_VERSION: "1.24"
  CGO_ENABLED: "1"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run tests
        run: go test -v ./...
